services:
  web:
    image: nginx
    volumes:
    - ./app:/var/www/html
    - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80
    networks:
      - backend
  php-fpm:
    image: php:8.3-fpm
    build:
      context: ./php-fpm
      dockerfile: Dockerfile 
    volumes:
      - ./app:/var/www/html
    networks:
      - backend
  db:
    image: mysql:8.4
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: secondp-db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: example
    networks:
      - backend

networks:
  backend:
    driver: bridge